version: "3.7"

# Hints:
# 1. docker-compose up --build
# 2. docker-compose run --rm app bundle install # if GemNotFound after 1
# 4. docker-compose run --rm app bash # to inspect from inside
services:
  app:
    command: ./scripts/dev-server.sh
    container_name: app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/log
      - node_modules:/app/node_modules
      - bundle:/bundle
      - /app/vendor/cache
    ports:
      - ${DEBUG_PORT}:${DEBUG_PORT}
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - postgres
    networks:
      - webnet

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - webnet
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - webnet
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:

volumes:
  bundle:
  node_modules:
  pgdata:
